<?php

/**
 * Implements hook_menu_alter()
 */
function helper_menu_alter(&$items)
{
  // убрать материалы с Главной
  $items['node']['page callback'] = 'helper_empty_front_page_callback';

  // убрать закладки со страницы входа
  // https://eureka.ykyuen.info/2011/01/31/drupal-remove-the-tabs-in-user-registration-form/
  $items['user']['type'] = MENU_CALLBACK;
  $items['user/register']['type'] = MENU_CALLBACK;
  $items['user/password']['type'] = MENU_CALLBACK;
}

/**
 * menu callback
 * убрать материалы с главной
 * @return array
 */
function helper_empty_front_page_callback()
{
  drupal_set_title('');
  return array();
}

/**
 * изменение формы поиска
 */
function helper_form_search_api_page_search_form_alter(&$form, &$form_state)
{
  $form['form']['keys_1']['#prefix'] = '<div class="input-group">';
  $form['form']['keys_1']['#title'] = '';
  $form['form']['keys_1']['#attributes']['class'][] = 'form-control';
  $form['form']['keys_1']['#attributes']['placeholder'] = 'Поиск';
  $form['form']['submit_1']['#prefix'] = '<span class="input-group-btn">';
  $form['form']['submit_1']['#value'] = 'Найти';
  $form['form']['submit_1']['#attributes']['class'][] = 'btn-brand';
  $form['form']['submit_1']['#suffix'] = '</span></div>';
}
